### ISSUE TITLE
Ownership of vercel link

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/nuxtjs-starter-buttercms#1]
Hi @gerzitom - can you either change the url for your currently deployed version of the nuxt.js app or transfer the ownership of the app to us (delete might be easiest?) That URL pattern matches what we're currently using for our "official" demo links, so we'd like to have that one :smile: 

Thanks!

**Comment by gerzitom** [comment]
@ViolanteCodes I have deleted my vercel project
