### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by orlyohreally** [ButterCMS/nuxtjs-starter-buttercms#11]
Overall looks good just some questions:
- I'm getting this error message when I build the app: https://share.getcloudapp.com/xQuwZzKz. Should that be fixed?
- Somewhere the imports are made using relative paths and some of them are not https://share.getcloudapp.com/rRuOvNEE. Is there a reason why?
- Is this page used https://github.com/ButterCMS/nuxtjs-starter-buttercms/blob/master/pages/test.vue?

**Comment by ViolanteCodes** [comment]
@orlyohreally I reached out to the dev for clarification on these points. Thanks as always for your amazing reviews :smiley:

**Comment by gerzitom** [comment]
@orlyohreally I have changed the imports to proper nuxt imports and removed the test page. About that issue, I was not able to figure out, how can I fix it. I only found out, that it involves globally imported CSS files and it is not able to analyze them. It might be some minor bug, but it does not affect this project.
