### ISSUE TITLE
Nuxt 3.3.0 support broken

### ISSUE THREAD

**Issue by saddam-azad** [ButterCMS/nuxtjs-starter-buttercms#14]
## Description

Cloning the repository and `npm install` results in an installation of `Nuxt v3.0.0-rc.3`  - and ButterCMS works as expected.

The strange issue that `package.json` refers to `nuxt3@latest` which should install `Nuxt 3.3.0` (true at the time of writing).

## To Reproduce

Replace the value of `nuxt` in `package.json` with `3.2.3` or above. Rerun `npm i`

`[Vue Warn] Component ButterCMS Nuxt Starter Project is missing template or render function.`

## Expected behavior

1. NPM should always install the latest Nuxt package.
2. ButterCMS should work on new stable version.

## Desktop
 - OS: Windows 11
 - Browser Firefox
 - Node 18

**Comment by orlyohreally** [comment]
@ViolanteCodes could you check this issue?
