### ISSUE TITLE
question re: env variable

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/nuxtjs-starter-buttercms#2]
The current env variable is listed as: NUXT_ENV_APP_BUTTER_CMS_API_KEY - this is a bit long and the pattern doesn't match our other projects. Is this because the NUXT_ENV_APP prefix is required by nuxt.js?

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes Yes, just prefix NUXT_ENV_ is preffered https://nuxtjs.org/docs/configuration-glossary/configuration-env/#automatic-injection-of-environment-variables
> 
> Sorry about that, I referred to Vue project https://github.com/ButterCMS/vuejs-starter-buttercms/blob/main/.env.example, Where this env variables are same just with `VITE` prefix. Should I shorten this variables as well?

Hi @gerzitom 

No problems!

For this app, if NUXT_ENV is a necessary prefix, can we just do NUXT_ENV_BUTTER_API_TOKEN?

**Comment by gerzitom** [comment]
@ViolanteCodes I have changed API KEY in #5
