### ISSUE TITLE
Draft changes not working for pages or menu items

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/nuxtjs-starter-buttercms#3]
[Video demo](https://share.getcloudapp.com/KouAov85)

Draft changes to pages and to menu items are not showing up in the app, even when local server is shut down and restarted. With the previewing function enabled (or not explicitly disabled), user should be seeing draft changes in their local app.

**Comment by gerzitom** [comment]
@ViolanteCodes it should be fixed in #4
