### ISSUE TITLE
Breadcrumb menu behavior is inconsistent

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/nuxtjs-starter-buttercms#6]
https://share.getcloudapp.com/bLuB17rp <-- the word "blog" with corresponding link sometimes disappears from the breadcrumb menu for categories and tags

**Comment by gerzitom** [comment]
@ViolanteCodes I have fixed the problem. Plus I have upgraded nuxt. So if you have any problems, try to remove all node_modules and install it again.
I have noticed, that I have left some unused files, which I am sorry for. So I have removed them.
