### ISSUE TITLE
Force trailing slashes

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/nuxtjs-starter-buttercms#7]
right now, routes both with and without trailing slashes work, e.g., /blog and /blog/
Is it possible to force trailing slashes here, so that routes always use trailing slashes once page loads?

If it's difficult / cumbersome, we can probably skip it - but we've had issues in the past with iframe preview + heroku if trailing slashes are not enforced, because of the way heroku handles proxy load balancing

@orlyohreally im going to tag you on this in case there's a follow up question while i'm on vacation

**Comment by gerzitom** [comment]
@ViolanteCodes Yes it can be done. I have written a nuxt middleware to do so. I have based this branch on my late #8 because I have ungraded Nuxt. If it was a problem, I can create this branch, when #8 will be merged.
